name: Auto Update Rules

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build-rules:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        # 确保找到正确的Python解释器
        $python = (Get-Command python).Source
        & $python -m pip install --upgrade pip
        & $python -m pip install requests
    
    - name: Create Build Directory
      run: New-Item -ItemType Directory -Path build -Force | Out-Null
      
    - name: Convert Rules
      run: python scripts/convert.py
      
    - name: Commit and Push
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add build/
        git commit -m "自动更新规则集 - $(Get-Date -Format 'yyyyMMdd_HHmm')"
        git push

    - name: Debug Python environment
      run: |
        Get-Command python | Format-List *
        pip list
        python -c "import sys; print(sys.path)"
