name: Auto Update Rules

on:
  schedule:
    - cron: '0 8 * * *'  # 每天UTC时间0点（北京时间8点）运行
  workflow_dispatch:       # 允许手动触发

jobs:
  build-rules:
    runs-on: windows-latest  # 使用Windows环境
    
    steps:
    # 1. 检出代码（包含所有分支和历史）
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整历史记录
    
    # 2. 设置Python环境
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    # 3. 安装Python依赖（重要！）
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    # 4. 创建构建目录
    - name: Create Build Directory
      run: New-Item -ItemType Directory -Path build -Force | Out-Null
      
    # 5. 运行转换脚本
    - name: Convert Rules
      env:
        PYTHONIOENCODING: utf-8  # 中文编码支持
      run: python scripts/convert.py
    
    # 6. 提交更新
    - name: Commit and Push
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add build/
        git commit -m "自动更新规则集 - $(Get-Date -Format 'yyyyMMdd_HHmm')"
        git push
