name: Auto Update Rules

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build-rules:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # 关键修改1：使用系统级安装（需要管理员权限）
    - name: Install dependencies as admin
      shell: powershell
      run: |
        # 以管理员身份安装依赖
        Start-Process -FilePath "$env:pythonLocation\python.exe" -ArgumentList "-m pip install --upgrade pip" -Verb RunAs -Wait
        Start-Process -FilePath "$env:pythonLocation\python.exe" -ArgumentList "-m pip install requests pyyaml" -Verb RunAs -Wait
        
    # 关键修改2：修复系统路径
    - name: Add Python to system PATH
      run: |
        $pythonPath = Join-Path -Path $env:pythonLocation -ChildPath "Scripts"
        echo "PYTHONPATH=$pythonPath;$pythonLocation" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "PATH=$pythonPath;$env:PATH" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        
    # 关键修改3：验证环境
    - name: Verify installation
      run: |
        python -c "import requests; print('导入requests成功：' + requests.__version__)"
        python -m pip list
      
    # 关键修改：使用指定路径运行脚本
    - name: Convert Rules
      run: |
        $pythonPath = Join-Path -Path $env:pythonLocation -ChildPath "python.exe"
        & $pythonPath scripts/convert.py
      
    - name: Commit and Push
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add build/
        git commit -m "自动更新规则集 - $(Get-Date -Format 'yyyyMMdd_HHmm')"
        git push

    - name: Verify environment
      run: |
        # 检查Python安装位置
        $pythonPath = Join-Path -Path $env:pythonLocation -ChildPath "python.exe"
        & $pythonPath --version
        
        # 检查请求模块安装位置
        & $pythonPath -c "import requests; print(requests.__file__)"
        
        # 检查系统路径
        echo "系统PATH:"
        echo $env:PATH
        
        # 检查用户模块路径
        & $pythonPath -c "import site; print('用户site-packages:', site.getusersitepackages())"
