name: Auto Update Rules

on:
  schedule:
    - cron: '0 8 * * *'  # 每天UTC时间0点（北京时间8点）运行
  workflow_dispatch:     # 允许手动触发

jobs:
  build-rules:
    runs-on: windows-latest  # 使用Windows环境
    
    steps:
    # 1. 检出代码
    - name: Checkout
      uses: actions/checkout@v4
      
    # 2. 安装Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    # 3. 运行转换脚本
    - name: Convert Rules
      run: |
        python scripts/convert.py
        
    # 4. 上传转换结果
    - name: Upload Rules
      uses: actions/upload-artifact@v4
      with:
        name: rules
        path: build/
        retention-days: 1
        
    # 5. 自动提交更新 (重要!)
    - name: Commit Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add build/*
        git commit -am "自动更新规则集 - $(Get-Date -Format 'yyyyMMdd_HHmm')"
        git push
